create extension if not exists pgcrypto;

create table if not exists public.morning_recipients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  kakao_name text not null,
  email text,
  content_type text not null check (content_type in ('5분 리프레시','크리스찬 말씀')),
  kakao_group int not null default 1 check (kakao_group between 1 and 8),
  kakao_enabled boolean not null default true,
  email_enabled boolean not null default true,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists morning_recipients_type_idx on public.morning_recipients(content_type, active);
create index if not exists morning_recipients_group_idx on public.morning_recipients(kakao_group);

create table if not exists public.morning_jobs (
  id uuid primary key default gen_random_uuid(),
  content_type text not null check (content_type in ('5분 리프레시','크리스찬 말씀')),
  subject text not null,
  message text not null,
  send_kakao boolean not null default true,
  send_email boolean not null default true,
  kakao_groups int[] not null default array[1,2,3,4,5,6,7,8],
  status text not null default 'pending' check (status in ('pending','running','completed','failed','cancelled')),
  created_by text not null default 'web',
  total_kakao int not null default 0,
  total_email int not null default 0,
  success_kakao int not null default 0,
  failed_kakao int not null default 0,
  success_email int not null default 0,
  failed_email int not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  agent_heartbeat_at timestamptz,
  completed_at timestamptz
);

create index if not exists morning_jobs_status_idx on public.morning_jobs(status, created_at);

create table if not exists public.morning_send_logs (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.morning_jobs(id) on delete cascade,
  channel text not null check (channel in ('kakao','email')),
  recipient_name text,
  address text,
  kakao_group int,
  status text not null check (status in ('success','failed','skipped')),
  detail text,
  created_at timestamptz not null default now()
);

create index if not exists morning_send_logs_job_idx on public.morning_send_logs(job_id, created_at);

alter table public.morning_recipients enable row level security;
alter table public.morning_jobs enable row level security;
alter table public.morning_send_logs enable row level security;

-- V4 web/API uses the Supabase service-role key only on the server side.
-- No anonymous/browser RLS policies are intentionally created.
